Parameters:
  DBInstanceClass:
    Type: String
    Default: db.t2.micro
    Description: DB instance class
    AllowedValues:
      - db.t2.micro
      - db.t2.medium
      - db.t2.large
      - db.m4.large
      - db.r4.large

Resources:
  DBInstance:
   Type: AWS::RDS::DBInstance
   Properties:
     DBName: PortfolioDB
     DBInstanceClass: db.t2.micro
     Engine: MySQL
     MasterUsername: admin
     MasterUserPassword: admin2369
     AllocatedStorage: 20
     StorageType: gp2
     MultiAZ: True
    #  AvailabilityZone: us-east-1c
     DBSubnetGroupName: !Ref DBSubnetGroup
     PubliclyAccessible: false
     VPCSecurityGroups:
       - !Ref DBSecurityGroup
     Tags:
       - Key: Name
         Value: MyRDSInstance

  DBSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
    GroupDescription: Open database for access
    # VpcId: !ImportValue newstack1-VPC
    VpcId: vpc-036eb7ca0f63c4471
    SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId:
        !ImportValue App-SecurityGroupWeb
    Tags:
      - Key: Name
        Value: MyDBSecurityGroup
      
  DBSubnetGroup:
   Type: AWS::RDS::DBSubnetGroup
   Properties:
     DBSubnetGroupDescription: "My DB Subnet Group"
     SubnetIds:
       - !ImportValue newstack1-PrivateSubnetC
       - !ImportValue newstack1-PrivateSubnetD
     Tags:
       - Key: Name
         Value: MyDBSubnetGroup


  # EnableReadReplica:
  #   Description: Enable the ReadReplica
  #   Type: String
  #   Default: 'true'
  #   AllowedValues: ['true', 'false']
  #   ConstraintDescription: must be true or false.

  ReplicaDB:
    Type: AWS::RDS::DBInstance
    # Condition: Enable-Read-Replica
    Properties:
      SourceDBInstanceIdentifier: !Ref DBInstance
      DBInstanceClass: !Ref 'DBInstanceClass'
      Tags:
      - Key: Name
        Value: Read Replica Database