AWSTemplateFormatVersion: '2010-09-09'
Description: Provides Session Manager access without an Internet Gateway to an existing instance in a private subnet.
Parameters:
  # Optional environment type
  EnvName:
    Type: String
    Description: 'The Environment type'
    Default: Dev

Resources:
  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:  
        - !Ref SSMInstanceSSMRole

  SSMInstanceSSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore

Outputs:
  SSMInstanceSSMRoleARN:
    Description: 'The ARN of the SSM Role'
    Value: !Ref SSMInstanceSSMRole
    Export:
      Name: !Sub "${EnvName}-SSMRoleARN"
  
  SSMInstanceProfile:
    Description: 'The ARN of the Instance Profile'
    Value: !GetAtt SSMInstanceProfile.Arn
    Export:
      Name: !Sub "${EnvName}-SSMInstanceProfile"